### ISSUE TITLE
'ZeroDivisionError: float division by zero' occuring when generating any noise

### ISSUE THREAD

**Issue by richgumy** [felixpatzelt/colorednoise#15]
The code I am trying to run should print out a histogram that proves central limit theorem that when you sum of several noise sources of different distributions you get a normal distribution
```python
import colorednoise as cnoise

noises = []
for i in range(100):
    noise = 0
    for n in range(3):
        noise = noise + cnoise.powerlaw_psd_gaussian(1,n) # order of the noise = n (n=0:white, n=1:pink, n=2:brown)
    noises.append(noise)

plt.hist(noises)
```

However I'm getting the following error:
```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[43], line 7
      5     noise = 0
      6     for n in range(3):
----> 7         noise = noise + cnoise.powerlaw_psd_gaussian(1,n) # order of the noise = n (n=0:white, n=1:pink, n=2:brown)
      8     noises.append(noise)
     10 plt.hist(noises)

File [c:\Users\.\AppData\Local\anaconda3\lib\site-packages\colorednoise.py:81](file:///C:/Users/./AppData/Local/anaconda3/lib/site-packages/colorednoise.py:81), in powerlaw_psd_gaussian(exponent, size, fmin, random_state)
     77 samples = size[-1]
     79 # Calculate Frequencies (we asume a sample rate of one)
     80 # Use fft functions for real output (-> hermitian spectrum)
---> 81 f = rfftfreq(samples)
     83 # Validate / normalise fmin
     84 if 0 <= fmin <= 0.5:

File [c:\Users\.\AppData\Local\anaconda3\lib\site-packages\numpy\fft\helper.py:218](file:///C:/Users/./AppData/Local/anaconda3/lib/site-packages/numpy/fft/helper.py:218), in rfftfreq(n, d)
    216 if not isinstance(n, integer_types):

I'm running python 3.10.9 and have used ```pip install colorednoise``` to install
    217     raise ValueError("n should be an integer")
--> 218 val = 1.0/(n*d)
    219 N = n//2 + 1
    220 results = arange(0, N, dtype=int)

ZeroDivisionError: float division by zero
```

Seems like a problem in the core algorithm somewhere. Thoughts?

I'm using python 3.10.9. Installed using ```pip install colorednoise```

**Comment by felixpatzelt** [comment]
You are trying to create a zero-sized time-series, that doesn't work. The signature is:
`powerlaw_psd_gaussian(exponent, size, **kwargs)`
I guess there could be a more specific error message, but it really doesn't make sense to create any super short time series with this package as it is meant specifically for long-range correlations. You wouldn't notice those in a super short time-series and could just use numpy.random instead. 

I also don't think I can get from the code you postet what you are actually trying to achiev. Are you sure you are not confusing correlation a distribution?

**Comment by richgumy** [comment]
Ok, I was thinking I could use this module to prove that when adding different types of noise together we always end up with a Gaussian distribution (as central limit theorem says).

I used your ```powerlaw_psd_gaussian()``` function incorrectly having the ```exponent``` and ```size``` around the wrong way, duh.  I just misinterpreted whether it could be used to find a single 'random' value from specific noise spectra, i.e. size = 1, which it is not made for.


Alaas the following code works:

```
import colorednoise as cnoise
import matplotlib.pyplot as plt
import numpy as np

n = 1000
noises = np.array([])

for i in range(n):
    noise = 0
    for x in range(3):
        noise = noise + cnoise.powerlaw_psd_gaussian(x,2) # order of the noise = n (n=0:white, n=1:pink, n=2:brown etc.)
    noises = np.append(noises,noise[0])

plt.hist(noises, bins=10)
```

![image](https://github.com/felixpatzelt/colorednoise/assets/14900898/f1c0cc6e-99f2-4d22-a377-fab40815aeac)

**Comment by felixpatzelt** [comment]
1. This module outputs arrays with noise with different correlations along one axis. This is useful particularly for time series with long-range correlations.
2. If you call this model repeatedly (as you do in your code), the results will not be correlated. In your code you have absolutely no benefit from using this module vs numpy.random.normal.
3. To sum over correlated random numbers, you need to create a bigger output and sum over that array, not using a loop.
4. The Central Limit Theorem (CLT) only holds for independent identically distributed random numbers. It does NOT hold for correlated random numbers.
5. In practice, you will usually have some convergence towards a Gaussian under _weak_ correlations, but it will be slowed down.
6. The CLT only holds for distributions with a finite mean and variance.
7. E.g. Brownian Noise does not have a finite mean unless there is some mean reversion. The sum over a brownian motion will diverge.
9. Some distributions do not have a finite variance (or finite mean), e.e. the Lévy distribution or the Cauchy Distribution. Here  the classic CLT will also not hold and you will not get convergence towards a Gaussian.
10. A numerical simulation is not a proof in the mathematical sense. If this is an exercise for a math class, your tutor will likely not accept that wording. You could call say you want to investigate, show or demonstrate something numerically.

**Comment by felixpatzelt** [comment]
For a very informal introduction to distributions and the CLT, see e.g. here: https://felixpatzelt.com/statistics-for-everyone/3_distributions.slides.html

**Comment by richgumy** [comment]
Ok thank you for you input. I've had a look at your slides for a basic understanding.
