### ISSUE TITLE
Fmin > 0.5 causes divide by 0 when exponent is positive

### ISSUE THREAD

**Issue by rbracco** [felixpatzelt/colorednoise#5]
This may be a lack of understanding of the underlying mechanics on my part, but I am getting back NaN and inf filled Arrays when setting fmin to any value > 0.5 when the exponent is positive. For white noise it doesn't cause NaN/inf, and a seemingly normal array is returned, by a FFT on the signal shows that frequencies below the minimum still appear to be present. 

Some examples of calls that will replicate
`powerlaw_psd_gaussian(2, 16000, fmin=100)`
`powerlaw_psd_gaussian(1, 16000, fmin=5)`
`powerlaw_psd_gaussian(0.1, 16000, fmin=1000)`

Examples of calls that will not cause error, but don't appear to remove the minimum frequency.
`powerlaw_psd_gaussian(0, 16000, fmin=100)`
`powerlaw_psd_gaussian(-1, 16000, fmin=5000)`

Please let me know if any additional info is needed. Thank you!

**Comment by felixpatzelt** [comment]
This is not well documented, but frequencies above 0.5 make no sense for the algorithm. The frequencies are generated by [numpy's rfftfreq](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.fft.rfftfreq.html) according to a sampling rate of one. That is, between 1/number_of_samples and 0.5. Hence, fmin=0.5 means you have white noise. Even larger fmin would mean a cutoff above the Nyquist frequency. Actually any fmin that is even close to 0.5 wouldn't make a lot of sense in a typical application of coloured noise. You can test it with the example code in the readme.

That being said, just returning infinity isn't very nice. I will introduce a meaningful error in a future release.

**Comment by rbracco** [comment]
Sorry, I was indeed misinterpreting it. I thought fmin was the minimum frequency present in the signal, so an exponent of 1 and fmin of 1000 would be pink noise with no energy in the range 0-1000hz, and a spectral profile consistent with fmin from 1000hz up to 1/2 the sample rate. Sorry for the mistake and thanks for the prompt reply.
